### ISSUE TITLE
Raidmode

### ISSUE THREAD

**Issue by ghost** [plexidev/issue-tracker#11]
I'm sorry for putting yet another suggestion in. I'm sure I'm just being a pain in the neck

My suggestion:

- Have a command such as "!raidmode" which will maybe for an example kick users after not completing a captcha after 15 min or something like that or send multiple captchas to newer users which will help when a server is getting raided. (These are just examples I know they aren't great)
- Maybe also have an "auto-raidmode" where if loads of users join at the same time it'll turn on raid mode automatically for a length of time.

Obviously, just a suggestion and it's fine if it ends up not being added:)

Thanks for making such an awesome bot:)

Thanks,
Maru#6818

**Comment by Zorotic** [comment]
We appreciate all suggestions!

This indeed could be a feature, but I won't be adding it because of false positives. However, I do plan on adding an option to kick users after a set period of time for not completing a captcha.
