### ISSUE TITLE
"Unverified" role

### ISSUE THREAD

**Issue by ghost** [plexidev/issue-tracker#14]
Instead of giving a user a role such as "verified" to get access to server channels maybe instead we could give users an "unverified" role (which doesn't have channel viewing perms) on joining which is taken wen the captcha is completed (thus giving it access to server channels).

This is just overall a better idea (or at least would be nice to have as an option) imo as it makes the channels cleaner without the lock symbol on every channel and also means its much much easier to lock channels with bots (during server maintenance and raids) and other such things as well as manage each channel's perms.

I'm sure others have also suggested for this so I'm sorry for being an annoyance if so. I think it'd just make the bot a million times better if this was made possible.

As always, thanks for offering such an awesome and free service and I hope this can help improve it. ٩( 'ω' )و

Maru

**Comment by Zorotic** [comment]
This is possible, but you have to think about the rate limits that will occur when a server gets raided or just casually.

As much as I would like to add this as it would in fact be a nice feature. It will simply just cause issues in my eyes.

As always. Thanks for the suggestions! 
- Zoro

**Comment by ghost** [comment]
ok that makes sense. Thanks anyways!
