### ISSUE TITLE
Unverifed role command

### ISSUE THREAD

**Issue by ghost** [plexidev/issue-tracker#19]
Make something like you need to set in config unverifed role then if someone will join server will get that role after that he needs to be verifed using !verify after verify he gets verifed role and then bot deletes unverifed role for that guy

**Comment by Bagszy** [comment]
Why? Also, this is a copy off https://github.com/plexidev/issue-tracker/issues/14

**Comment by ghost** [comment]
Oh i didnt know sorry

**Comment by ghost** [comment]
I was thinking that im first with this idea so ill close it
