### ISSUE TITLE
Server count on top.gg/bot/captcha stuck on "2 servers"

### ISSUE THREAD

**Issue by lorencerri** [plexidev/issue-tracker#3]
https://top.gg/bot/captcha

Image:
![](https://i.plexidev.org/bGK9YZP)

**Comment by Zorotic** [comment]
Will look into this asap.

**Comment by Zorotic** [comment]
I've reset the api token and will be pushing to prod momentarily to see if this resolves the issue.

**Comment by lorencerri** [comment]
Seems to be fixed

**Comment by Zorotic** [comment]
I'm working on a long term solution to this problem, it can be found [here](https://github.com/ZoroSC/micropost)

**Comment by Zorotic** [comment]
This has since been fixed.
