### ISSUE TITLE
Joining two servers with Server Captcha bot and getting the captcha from both servers will only put the captcha for the last server you joined.

### ISSUE THREAD

**Issue by anandsrinivasangithub** [plexidev/issue-tracker#31]
Reproduction steps
- Join two servers with Server Captcha bot
- Get the captcha from both
- Try completing the first captcha
- Observe

Expected Result: You are able to complete the captcha from both. If your answer doesn't match either one of the captchas, it should say that it's wrong.

Actual Result: You are only able to complete the last captcha that it sent.

This is quite an annoying bug.

**Comment by Zorotic** [comment]
This is intentional behavior.

Therefore this is not a bug, Nevertheless thanks for reporting it.
