### ISSUE TITLE
Captcha is not Always Sent to Users

### ISSUE THREAD

**Issue by andrewathalye** [plexidev/issue-tracker#36]
I have on multiple occasions received Server Captcha Bot messages that don't actually have a captcha attached, leaving just a blank space where it should theoretically be. Attached is an example screenshot.

System Information: I have tested this on x86_64 Linux Discord Canary, ARM64 AOSP Android Discord Alpha, and the stable web versions for my Discord account. I do not have access to any Discord accounts to test with, but if any developers need my username + discriminant to test anything I can send it to you, I just would prefer not to leave it in an issue.

I have 2FA on and the classic Discord theme enabled as well (as known as Compact).
![Discord Captcha Bot](https://user-images.githubusercontent.com/30047830/128529620-267aedbc-b5d7-41fc-9e7b-9731dab82ad5.png)

**Comment by andrewathalye** [comment]
I have just tried using the default theme as well and it appears to make no difference. If you're got any suggestions or there is something that I am obviously doing wrong, please let me know and I'll gladly close the issue.

**Comment by ImDarkDiamond** [comment]
![image](https://user-images.githubusercontent.com/43022364/128535776-f2a67c64-a53b-465e-a300-e9fd8fd8e257.png)
This is not an issue with the bot. It's an issue with your client settings.

**Comment by andrewathalye** [comment]
Thank you, I was not aware that that was an option but I'll be sure to check more carefully in the future.
