### ISSUE TITLE
Can you guys fix user.id banning?

### ISSUE THREAD

**Issue by Kief5555** [plexidev/issue-tracker#38]
I just got banned by typing in user.id and the mod bot thought I was a malware link

**Comment by lorencerri** [comment]
Hello, I apologize for that! We were testing out a new system that detects malware & phishing links and it seems that Kaspersky detected the URL as malware. We've gone ahead and made it so moderators now have to manually ban after reviewing the links. You should be unbanned now and you can rejoin using this link: https://discord.gg/plexidev
